ci:
  skip: [pytest]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: check-toml
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pytest
        name: Check pytest
        entry: pytest --cov=hackcqooc --cov-report=html --cov-fail-under=90 --cov-config ./tests/.coveragerc
        pass_filenames: false
        language: system
        types: [python]
