name: PyPI publish CI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: "Installs dependencies"
        run: |
          python3 -m pip install --upgrade rye
          rye sync
      - name: "Builds and uploads to PyPI"
        run: |
          rye build
          rye publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PIPY }}
